### ISSUE TITLE
Load specific waypoint

### ISSUE THREAD

**Issue by Colmill0** [JaymZZZZ/VA-Datatape#2]
Hello there
Thank you very much for the work you did and for keeping the changes up to date.
In the sqn. in which I fly we use it a lot and we are very satisfied with it.
But we couldn't get "load datatape waypoint (steerpoint) xx" to work
VA recognizes the command, but only moves the swt to RET 2 times and activates the "Steer Point Loaded" audio.
I have not made any changes to the configuration, what do you think it could be?
Thanks in advance

**Comment by JaymZZZZ** [comment]
I believe this has been reported before. I'll try and release a fix tonight.

**Comment by Colmill0** [comment]
Thank you!! 
Cheers

**Comment by Colmill0** [comment]
Wow, fast update and works Perfect!!
Than you very much
